"""Materialize the approved layout as an editable HTML build source."""
from pathlib import Path
from html import escape
ROOT=Path(__file__).resolve().parents[1]
CSS='''
:root{color-scheme:light;--page:#ffffff;--text:#24211e;--muted:#70675d;--border:#ded8cf;--accent:#9a661b;--gold:#d6a03b;--chip:#f6f2ea}
:root[data-theme=dark]{color-scheme:dark;--page:#161719;--text:#f4f0e9;--muted:#bfb6a8;--border:#3a3732;--accent:#e2b45d;--gold:#e0a62f;--chip:#25231f}
*{box-sizing:border-box}body{margin:0;background:var(--page);color:var(--text);font-family:system-ui,-apple-system,"Segoe UI","Noto Sans CJK SC","Microsoft YaHei",sans-serif;-webkit-font-smoothing:antialiased}a{color:inherit;text-decoration:none}svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round;flex-shrink:0}
.sample{margin:0 auto;max-width:984px;padding:34px 42px 28px;background:var(--page)}.banner{display:block;width:100%;height:auto}.intro{text-align:center;padding:27px 6px 22px}.typing{color:var(--accent);font-size:30px;font-weight:650;min-height:58px;line-height:1.65;margin:0 0 15px}.description{font-size:16px;line-height:1.9;color:var(--muted);margin:0 auto;max-width:740px}.nav{display:flex;flex-wrap:wrap;justify-content:center;gap:10px;margin:25px auto 7px}.nav a{width:138px;display:inline-flex;align-items:center;justify-content:center;gap:10px;height:43px;background:var(--chip);border:1px solid var(--border);border-radius:9px;font-size:14px;font-weight:550}.nav svg{color:var(--accent)}
.work-section{padding:20px 0 4px}.work-heading,.next-heading,.tail-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:18px;margin:0 0 24px}.work-eyebrow,.next-eyebrow,.tail-eyebrow{font:11px/1.5 ui-monospace,SFMono-Regular,Consolas,monospace;letter-spacing:.15em;color:var(--accent);margin:0 0 7px}.work-heading h2,.next-heading h2,.tail-heading h2{font-size:29px;letter-spacing:-.035em;line-height:1.35;margin:0;font-weight:670}.work-all,.next-caption,.tail-more{color:var(--muted);font-size:12px;display:flex;align-items:center;gap:7px;white-space:nowrap}
.work-feature-grid,.work-compact-grid,.stats-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:18px}.work-feature{min-width:0;background:var(--chip);border:1px solid var(--border);border-radius:12px;overflow:hidden}.work-art{margin:0;position:relative;background:#f7f4ee;border-bottom:1px solid var(--border)}.work-art img{display:block;aspect-ratio:16/9;width:100%;height:auto;object-fit:contain}.work-art figcaption{position:absolute;bottom:10px;right:10px;padding:3px 8px;background:#f7f4eef2;color:#514a40;border:1px solid #d9cdbc;font-size:10px;border-radius:4px}.work-feature-copy{padding:20px 22px 0}.work-kicker{display:flex;align-items:center;justify-content:space-between;color:var(--accent);font-size:11px;letter-spacing:.04em}.work-kicker span{color:var(--muted);font-size:10px;border:1px solid var(--border);padding:2px 7px;border-radius:4px}.work-feature h3{margin:9px 0 11px;font-size:25px;line-height:1.25;font-weight:650;letter-spacing:-.03em}.work-desc{font-size:14px;line-height:1.8;color:var(--text);margin:0}.work-feature .work-desc{min-height:51px}.work-detail{font-size:12px;line-height:1.8;color:var(--muted);margin:9px 0 18px}.work-actions{border-top:1px solid var(--border);display:flex;justify-content:space-between;padding:15px 0;font-size:12px}.work-actions a{color:var(--accent)}
.work-minor-heading{display:flex;align-items:center;gap:15px;margin:30px 0 15px;font-size:12px;color:var(--muted)}.work-compact{min-width:0;border:1px solid var(--border);padding:19px 21px 16px;border-radius:10px}.work-compact-title{display:flex;align-items:center;gap:10px;margin:0 0 10px}.work-compact-title>svg{color:var(--accent)}.work-compact h3{font-size:17px;line-height:1.5;letter-spacing:-.015em;margin:0;font-weight:630}.work-compact .work-desc{font-size:13px;min-height:47px;color:var(--muted)}.work-compact-foot{font-size:11px;display:flex;gap:10px;justify-content:space-between;align-items:center;margin-top:17px}.work-compact-foot>span{color:var(--muted)}.work-compact-foot>a{color:var(--accent)}.work-footer{margin-top:27px;padding-top:20px;border-top:1px solid var(--border);font-size:12px;color:var(--muted)}.work-footer a{color:var(--accent)}
.new-sections{padding-top:35px}.tool-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:13px}.tool-tile{min-width:0;border:1px solid var(--border);border-radius:10px;padding:20px 19px 18px;display:grid;grid-template-columns:38px 1fr;grid-template-rows:auto auto;gap:3px 13px;align-items:center}.tool-logo{grid-row:1/3;display:grid;place-items:center;width:35px;height:38px;color:var(--accent)}.tool-logo svg{width:31px;height:31px}.tool-name{font-size:13px;line-height:1.5;font-weight:630;white-space:nowrap}.tool-use{font-size:11px;line-height:1.6;color:var(--muted)}.tool-note,.stats-footnote{font-size:11px;line-height:1.9;color:var(--muted);margin:13px 1px 0}.section-break,.tail-rule{display:flex;align-items:center;gap:12px;margin:33px 0 30px}.section-break span,.tail-rule span{height:1px;flex:1;background:var(--border)}.section-break i,.tail-rule i{width:5px;height:5px;border-radius:50%;background:var(--gold)}
.stat-card{border:1px solid var(--border);border-radius:12px;overflow:hidden;background:var(--chip);display:flex;flex-direction:column;min-width:0}.stat-heading{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:20px 22px 16px}.stat-title{display:flex;align-items:center;gap:9px;color:var(--accent)}.stat-title h3{margin:0;font-size:17px;line-height:1.4;font-weight:630;color:var(--text)}.stat-source{font-size:10px;border:1px solid var(--border);border-radius:4px;color:var(--muted);padding:3px 7px;white-space:nowrap}.stat-body{flex:1;min-height:226px;padding:0 22px 18px;display:flex;flex-direction:column;justify-content:center}.stat-footer{border-top:1px solid var(--border);padding:13px 20px;display:flex;justify-content:space-between;align-items:center;gap:8px;font-size:10px;color:var(--muted);line-height:1.7}.stat-footer a{color:var(--accent)}.stat-live-image{display:block;width:100%;height:auto;max-width:100%;border-radius:5px}.activity-extension{margin-top:22px}.activity-extension .stat-body{min-height:120px;padding:18px 20px;align-items:center}.activity-extension .stat-live-image{max-width:540px}
.tail-sections{padding-top:28px}.tail-post-link{display:flex;gap:24px;align-items:center;padding:25px 0;border-top:1px solid var(--border)}.tail-post-link:last-child{border-bottom:1px solid var(--border)}.tail-entry-number{display:grid;place-items:center;flex-shrink:0;width:32px;height:34px;background:var(--chip);border:1px solid var(--border);border-radius:6px;color:var(--accent);font:11px ui-monospace,monospace}.tail-entry-content{flex:1;min-width:0}.tail-post-meta{display:flex;gap:15px;align-items:center;color:var(--accent);font-size:11px}.tail-post-meta time,.tail-pr-bottom{font:10px/1.8 ui-monospace,monospace;color:var(--muted)}.tail-entry-content h3{margin:10px 0 10px;font-size:19px;line-height:1.5;font-weight:650;letter-spacing:-.02em}.tail-entry-content p{margin:0;color:var(--muted);font-size:13px;line-height:1.9}.tail-open{color:var(--accent);margin-right:16px}.tail-contributions{margin-top:40px}.tail-pr{position:relative;display:flex;gap:24px}.tail-pr-node{position:relative;flex-shrink:0;display:grid;place-items:center;width:32px;height:32px;border:1px solid var(--border);border-radius:50%;color:var(--accent);background:var(--page)}.tail-pr:not(:last-child):before{content:"";position:absolute;left:15px;top:32px;bottom:0;width:1px;background:var(--border)}.tail-pr-content{min-width:0;flex:1;padding:0 0 25px;margin:0 0 25px;border-bottom:1px solid var(--border)}.tail-pr:last-child .tail-pr-content{border:0;margin-bottom:0}.tail-pr-meta{display:flex;align-items:center;justify-content:space-between;gap:10px}.tail-pr-repo{font:12px/1.6 ui-monospace,monospace;color:var(--accent);overflow-wrap:anywhere}.tail-merged{font-size:10px;color:var(--accent);border:1px solid var(--border);background:var(--chip);padding:3px 8px;border-radius:4px;white-space:nowrap}.tail-pr h3{margin:12px 0 9px;font-size:18px;line-height:1.5;font-weight:630}.tail-pr p{margin:0 0 11px;font-size:13px;line-height:1.9;color:var(--muted)}.tail-pr-bottom{display:flex;justify-content:space-between;align-items:center}.tail-pr-open{font:11px/1.8 system-ui;color:var(--accent)}
.tail-contact{margin-top:17px;padding:28px;background:var(--chip);border:1px solid var(--border);border-radius:12px}.tail-contact-main{display:flex;align-items:center;justify-content:space-between;gap:30px}.tail-contact h2{font-size:29px;line-height:1.4;margin:7px 0 14px;letter-spacing:-.035em}.tail-contact-copy{font-size:13px;color:var(--muted);line-height:1.9;margin:0}.tail-contact-right{width:50%}.tail-email{display:flex;gap:12px;align-items:center;font-size:20px;font-weight:650}.tail-email svg{color:var(--accent);width:20px;height:20px}.tail-socials{display:flex;gap:8px;margin-top:20px}.tail-social{border:1px solid var(--border);border-radius:5px;padding:7px 10px;font-size:11px;background:var(--page);color:var(--muted)}.tail-end{margin-top:27px;padding-top:17px;border-top:1px solid var(--border);display:flex;justify-content:space-between;font:11px ui-monospace,monospace;color:var(--muted)}
@media(max-width:900px){.tool-tile{padding:17px 12px;gap:3px 9px;grid-template-columns:30px 1fr}.tool-logo,.tool-logo svg{width:27px}.tool-name{font-size:12px}}
@media(max-width:680px){.sample{margin:0 10px;padding:14px 13px 12px}.intro{padding:22px 0 17px}.typing{font-size:22px;min-height:72px}.description{font-size:14px}.nav{gap:8px}.nav a{width:124px;height:41px;font-size:13px}.work-feature-grid,.work-compact-grid,.stats-grid{grid-template-columns:minmax(0,1fr);gap:15px}.work-feature .work-desc,.work-compact .work-desc{min-height:0}.work-feature-copy{padding:18px 19px 0}.work-feature h3{font-size:24px}.work-compact{padding:18px 19px 15px}.work-compact-foot{margin-top:12px}.work-heading h2,.next-heading h2,.tail-heading h2{font-size:25px}.work-eyebrow,.next-eyebrow,.tail-eyebrow{font-size:10px}.work-all,.tail-more,.next-caption{font-size:11px}.tool-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.tool-tile{padding:17px 13px;grid-template-columns:29px 1fr;gap:3px 10px}.tool-name{font-size:12px}.tool-use{font-size:10px}.stat-heading{padding:20px 19px 14px}.stat-title h3{font-size:16px}.stat-body{padding:0 19px 17px;min-height:222px}.stat-footer{padding:12px 18px}.tail-post-link{gap:13px;padding:22px 0;align-items:flex-start}.tail-entry-number{width:26px;height:29px;margin-top:4px}.tail-entry-content h3{font-size:17px}.tail-entry-content p,.tail-pr p{font-size:12px}.tail-open{display:none}.tail-pr{gap:13px}.tail-pr-node{width:26px;height:27px}.tail-pr:not(:last-child):before{left:12px;top:27px}.tail-pr-meta{align-items:flex-start}.tail-pr-repo{font-size:10px}.tail-pr h3{font-size:16px}.tail-contact{padding:22px 19px}.tail-contact-main{flex-direction:column;align-items:flex-start;gap:23px}.tail-contact-right{width:100%}.tail-email{font-size:18px}.tail-contact h2{font-size:25px}.tail-contact-copy{font-size:12px}}
@media(max-width:360px){.tool-tile{padding:14px 10px;gap:3px 7px;grid-template-columns:25px 1fr}.tool-logo,.tool-logo svg{width:24px}.tool-name{font-size:11px}}
'''
PATHS={
'link':'<path d="M9 5H5v14h14v-4M13 3h8v8M21 3 10 14"/>',
'code':'<path d="m8 5-6 7 6 7m8-14 6 7-6 7M14 3l-4 18"/>',
'web':'<circle cx="12" cy="12" r="9"/><path d="M3 12h18M12 3c5 5 5 13 0 18-5-5-5-13 0-18Z"/>',
'book':'<path d="M12 21V5M3 3c4-1 7 0 9 2 2-2 5-3 9-2v16c-4-1-7 0-9 2-2-2-5-3-9-2Z"/>',
'box':'<path d="m12 2 9 5v10l-9 5-9-5V7l9-5ZM3 7l9 5 9-5M12 12v10"/>',
'file':'<path d="M6 3h9l4 4v14H6zM14 3v5h5M9 12h7M9 16h7"/>',
'mail':'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',
'merge':'<circle cx="6" cy="4" r="2"/><circle cx="6" cy="20" r="2"/><circle cx="18" cy="6" r="2"/><path d="M6 6v12m12-10v1c0 4-5 7-12 7"/>',
'arrow':'<path d="M5 12h14m-6-6 6 6-6 6"/>',
'grid':'<rect x="3" y="3" width="18" height="18" rx="3"/><path d="M3 9h18M9 9v12"/>',
}
def icon(name):return '<svg viewBox="0 0 24 24" aria-hidden="true">'+PATHS[name]+'</svg>'
def anchor(url,label):return f'<a href="{escape(url,quote=True)}">{label}</a>'
def heading(cls,num,en,title,right='',url=''):
 right=anchor(url,right+icon('link')) if url else right
 return f'<header class="{cls}-heading"><div><p class="{cls}-eyebrow">{num} / {en}</p><h2>{title}</h2></div><span class="{cls}-more work-all next-caption">{right}</span></header>'
BASE='https://github.com/lora-sys/'
features=[('Glassbox','Glassbox-Agent-Harness','glassbox','PERSONAL AGENT','开发中','开发中的个人 Agent 工作台，管理对话、权限与任务执行。','当前在做 QQ 接入与任务执行流程。'),('Zhihu Threads','zhihu-threads','zhihu','LEARNING APP','应用','把选中的知乎摘录整理成带来源的学习线，支持追问、自测和导出。','用户选来源，AI 基于所选摘录回答。')]
compact=[('AgentArena','AgentArena','grid','让三支 Agent 团队处理同一任务，保留提案、证据与对战回放。','多 Agent 实验',BASE+'AgentArena','查看项目'),('Lora Skills','skills','box','按需安装的 Agent 工作流集合，涵盖工程、写作和内容发布。','可安装工具',BASE+'skills#安装','查看安装说明'),('nano-vLLM 交互教程','nano-vllm-interactive-guide','book','结合源码与浏览器实验，讲解推理调度、KV Cache 和采样。','交互式源码教程','https://lora-sys.github.io/nano-vllm-interactive-guide/guide/00-start','打开教程'),('Free Vision Skill','free-vision-skill','code','按任务提取图片中的相关信息，输出文本证据供 Agent 继续处理。','开发者工具',BASE+'free-vision-skill#使用','查看使用方式')]
articles=[('agent-budget-memory-evaluation','论文阅读','2026.09.16','Agent 该继续跑，还是重新开一轮？','同样一笔预算，是继续当前会话，还是重新尝试？结合记忆与评测拆解这个问题。'),('tau-agent-architecture','架构与源码','2026.09.16','把 AI Agent 拆成三层','以 Tau 为例，拆开模型适配、Agent 核心和应用界面，说明每一层负责什么。'),('ai-engineering-harness','工程实践','2026.08.02','Agent 开发的测试与审查','把 Issue、实现、测试、代码审查和验收记录组织成一次可检查的交付。')]
prs=[('cloudwego/eino-examples',227,'2026.05.25','修复 Excel Agent 的计划与文件路径','修正启动路径重复、计划步骤为空，以及文件工具写入目录不正确的问题。'),('portdeveloper/nad-agent',49,'2026.08.18','增加多账户切换与配置持久化','在命令行列出和切换账户，保存当前选择，并让转账使用选中的账户。'),('nishuzumi/moss',29,'2026.07.19','增加合约 ABI 获取工具','获取已验证的合约 ABI，生成 TypeScript 定义，并处理参数校验、错误与密钥脱敏。')]
# These are the approved local icon geometries, not a downloaded font.
tool_shapes=[
'<rect x="3" y="3" width="26" height="26" rx="3"/><text x="16" y="22" text-anchor="middle" font-size="13" font-weight="750" stroke="none" fill="currentColor">TS</text>',
'<path d="m16 2 12 7v14l-12 7L4 23V9Z"/><text x="16" y="21" text-anchor="middle" font-size="13" stroke="none" fill="currentColor" font-weight="650">N</text>',
'<ellipse cx="16" cy="16" rx="14" ry="5"/><ellipse cx="16" cy="16" rx="14" ry="5" transform="rotate(60 16 16)"/><ellipse cx="16" cy="16" rx="14" ry="5" transform="rotate(120 16 16)"/><circle cx="16" cy="16" r="2.5" fill="currentColor" stroke="none"/>',
'<path d="M5 12c3-7 10-7 13-2s7 4 10 0c-3 7-10 7-13 2s-7-4-10 0ZM2 22c3-7 10-7 13-2s7 4 10 0c-3 7-10 7-13 2s-7-4-10 0Z" stroke="none" fill="currentColor"/>',
'<ellipse cx="16" cy="7" rx="10" ry="4"/><path d="M6 7v17c0 5 20 5 20 0V7M6 15c0 5 20 5 20 0"/>',
'<path d="m16 2 12 7v14l-12 7L4 23V9Z"/><path d="M21 10H11v12h10m-10-6h8"/>',
'<path d="m18 2-8 14h7l-3 9L29 9H18l3-7M3 20l6 7 9-10"/>',
'<path d="M4 6c4 2 10 2 14 0v8c0 7-7 10-7 10s-7-3-7-10ZM18 11l10-3v10c0 7-6 11-6 11s-3-1-5-4M7 12h2m4 0h2m-7 5c2 2 4 2 6 0M21 15h2m-2 6 3-1"/>']

def write():
 out=['<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><title>Lora approved profile</title><style>'+CSS+'</style></head><body><main class="sample">']
 out+=['<img class="banner" src="assets/banner.webp" alt="原版 Lora 与 Mochi banner"><section class="intro"><p class="typing">你好，我是 Lora。</p><p class="description">我做 AI 应用和开发者工具，也把读源码的过程做成交互教程。<br>正在开发 Glassbox，研究个人 Agent 的记忆、权限与任务执行。</p><nav class="nav">']
 for label,url,ic in [('个人网站','https://lora-sys.github.io/loraSys/','web'),('项目','https://lora-sys.github.io/loraSys/projects','grid'),('文章','https://lora-sys.github.io/loraSys/blog','file'),('联系我','mailto:lorasys@outlook.com','mail')]:out.append(anchor(url,icon(ic)+label))
 out+=['</nav></section><section class="work-section">',heading('work','01','SELECTED WORK','项目与作品','浏览全部项目','https://lora-sys.github.io/loraSys/projects'),'<div class="work-feature-grid">']
 for title,repo,art,kind,status,desc,detail in features:
  out.append(f'<article class="work-feature"><figure class="work-art"><a href="{BASE+repo}"><img src="assets/{art}.webp" alt="{title} 现有项目插画，非产品截图"></a><figcaption>项目插画</figcaption></figure><div class="work-feature-copy"><div class="work-kicker">{kind}<span>{status}</span></div><h3>{anchor(BASE+repo,title)}</h3><p class="work-desc">{desc}</p><p class="work-detail">{detail}</p><div class="work-actions">{anchor(BASE+repo,"查看仓库")}</div></div></article>')
 out+=['</div><div class="work-minor-heading">工具、实验与教程</div><div class="work-compact-grid">']
 for title,repo,ic,desc,kind,url,label in compact:out.append(f'<article class="work-compact"><div class="work-compact-title">{icon(ic)}<h3>{anchor(BASE+repo,title)}</h3></div><p class="work-desc">{desc}</p><div class="work-compact-foot"><span>{kind}</span>{anchor(url,label)}</div></article>')
 out+=['</div><footer class="work-footer">'+anchor(BASE+'ai-engineering-harness','AI Engineering Harness')+' · 更多工程工作流见仓库。</footer></section><section class="new-sections"><section class="tool-section">',heading('next','02','TOOLKIT','技术与工具','项目中使用'),'<div class="tool-grid">']
 for i,(name,use) in enumerate([('TypeScript','应用逻辑'),('Node.js','服务端运行'),('React','界面与交互'),('Tailwind CSS','样式与布局'),('SQLite','本地存储'),('Effect TS','异步流程'),('Vitest','逻辑测试'),('Playwright','浏览器验证')]):
  repo='Glassbox-Agent-Harness' if i in (1,6,7) else 'zhihu-threads'
  out.append(f'<a class="tool-tile" href="{BASE+repo}/blob/main/package.json"><span class="tool-logo"><svg viewBox="0 0 32 32">{tool_shapes[i]}</svg></span><span class="tool-name">{name}</span><span class="tool-use">{use}</span></a>')
 out+=['</div><p class="tool-note">用于应用开发、数据存储和测试。点击图标可查看项目依赖。</p></section><div class="section-break"><span></span><i></i><span></span></div><section class="stats-section">',heading('next','03','GITHUB ACTIVITY','代码与贡献','lora-sys'),'<div class="stats-grid">']
 for key,title in [('stats','GitHub 总览'),('languages','仓库语言分布'),('streak','连续贡献记录')]:
  if key=='streak':out.append('</div>')
  src='Stats Fast' if key=='stats' else '自托管服务'
  url='https://github-readme-stats-fast.vercel.app/api?username=lora-sys' if key=='stats' else ('https://github-readme-stats-sigma-fawn-45.vercel.app/api/top-langs/?username=lora-sys' if key=='languages' else 'https://github-readme-streak-stats-eight.vercel.app/?user=lora-sys')
  out.append(f'<article class="stat-card {"activity-extension" if key=="streak" else ""}" id="{key}-card"><header class="stat-heading"><div class="stat-title">{icon("book" if key=="stats" else "code")}<h3>{title}</h3></div><span class="stat-source">每日更新</span></header><div class="stat-body" id="{key}-body"></div><footer class="stat-footer"><span {"id=overview-provider-label" if key=="stats" else ""}>{src}</span>{anchor(url,"查看原始图片")}</footer></article>')
 out+=['</section></section><section class="tail-sections"><div class="tail-rule"><span></span><i></i><span></span></div><section class="tail-writing">',heading('tail','04','FIELD NOTES','文章与笔记','全部文章','https://lora-sys.github.io/loraSys/blog'),'<div class="tail-posts">']
 for i,(slug,kind,date,title,desc) in enumerate(articles):out.append(f'<a class="tail-post-link" href="https://lora-sys.github.io/loraSys/blog/{slug}"><span class="tail-entry-number">0{i+1}</span><div class="tail-entry-content"><div class="tail-post-meta"><span>{kind}</span><time>{date}</time></div><h3>{title}</h3><p>{desc}</p></div><span class="tail-open">{icon("arrow")}</span></a>')
 out+=['</div></section><section class="tail-contributions">',heading('tail','05','OPEN SOURCE','参与的开源项目','更多合并记录','https://github.com/search?q=author%3Alora-sys+is%3Apr+is%3Amerged&type=pullrequests'),'<div class="tail-timeline">']
 for repo,num,date,title,desc in prs:
  url=f'https://github.com/{repo}/pull/{num}'
  out.append(f'<article class="tail-pr"><span class="tail-pr-node">{icon("merge")}</span><div class="tail-pr-content"><div class="tail-pr-meta"><a class="tail-pr-repo" href="{url}">{repo}</a><span class="tail-merged">已合并</span></div><h3>{anchor(url,title)}</h3><p>{desc}</p><div class="tail-pr-bottom"><time>{date}</time><a class="tail-pr-open" href="{url}">查看 PR #{num} {icon("link")}</a></div></div></article>')
 out+=['</div></section><footer class="tail-contact"><div class="tail-contact-main"><div class="tail-contact-text"><p class="tail-eyebrow">06 / CONTACT</p><h2>联系我</h2><p class="tail-contact-copy">项目问题请在对应仓库提 Issue。<br>其他交流可以发邮件。</p></div><div class="tail-contact-right"><a class="tail-email" href="mailto:lorasys@outlook.com">'+icon('mail')+'<span>lorasys@outlook.com</span></a></div></div></footer></section></main></body></html>']
 dest=ROOT/'assets/profile/approved-layout.html';dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text('\n'.join(out),encoding='utf-8')
if __name__=='__main__':write()
